[zh-tw]
  languageName = "正體中文"
  weight = 1
  [zh-tw.params]
    dateFormat = "2006-01-02"
    description = "程式X語言X筆記X心得 - Find a way, Make a day"
    keywords = " Blog, C, C++, Java, 心得, Hugo, Bootstrap"
    [zh-tw.params.archive]
      dateFormat = "01-02"
