[[main]]
  name = "更多"
  identifier = "support"
  weight = 40
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
[[main]]
  name = "Repository"
  identifier = "repository"
  parent = "support"
  url = "https://github.com/rerepopo/"
  weight = 1
[[main]]
  parent = "support"
  weight = 4
  [main.params]
    divider = true

[[footer]]
  name = "Support"
  identifier = "support"
  weight = 1
[[footer]]
  name = "Repository"
  identifier = "repository"
  parent = "support"
  url = "https://github.com/rerepopo/"
  weight = 1
  pre = '<i class="fab fa-fw fa-github"></i>'

[[footer]]
  name = "Docs"
  identifier = "docs"
  weight = 2

[[footer]]
  name = "Features"
  identifier = "features"
  weight = 3

[[footer]]
  identifier = "demo"
  name = "Demo"
  weight = 4
[[footer]]
  identifier = "demo-netlify"
  parent = "demo"
  name = "Netlify"
  weight = 1
  url = "https://hbs.razonyang.com"
[[footer]]
  identifier = "demo-china"
  parent = "demo"
  name = "China"
  weight = 2
  url = "https://hbs-cn.razonyang.com"
