email = "example@email.com"
facebook = ""
github = "rerepopo"
# gitlab = "yourgitlabusername"
linkedin = ""
# stackoverflow = "yourstackoverflowuserid"
# twitter = "yourtwitterusername"
# weibo = "yourweibousername"
# zhihu = "yourzhihuusername"
instagram = ""
# quora = "yourquorausername"
# tumblr = "yourtumblrusername"
# reddit = "yourredditusername"
# telegram = "yourtelegramusername"
# qq = "yourqqnumber"
# dockerhub = "yourdockerhubusername"
# bitbucket = "yourbitbucketworkspaceid"
# kaggle = "yourkaggleusername"
# medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm = "yourlastfmusername"
# bilibili = "yourbilibiliuserid"
youtube = ""
# discord = "yourdiscordinvitecode"
# discourse = "https://yourforum.tld"
# facebookgroup = "yourfacebookgroupname"
# tiktok = "yourtiktokusername"
# pinterest = "yourpinterestusername"
# mastodon = "yourmastodonusername"
